### ISSUE TITLE
enhancement: stop spam by putting a cooldown of 180 seconds per mention of a pokemon

### ISSUE THREAD

**Issue by gitGremlin** [quarterto/slack-pokedex#4] opened 2016-07-18 14:27 UTC
If the pokemon was already called in the last 180 seconds, don't post an image.

Potential issue: if you type 'pidgey' every 175 seconds, you'll never see a pidgey.
![casey_pidgey](https://cloud.githubusercontent.com/assets/12858421/16918081/0de344bc-4cfc-11e6-9b80-cfad37d39244.png)

**Comment by apaleslimghost** [comment] 2016-07-18 14:50
duplicate of #1

**Closed as completed by apaleslimghost** 2016-07-18 14:50 UTC

**Comment by gitGremlin** [comment] 2016-07-18 14:54
👍
